"""initial control plane schema

Revision ID: ddf7460703a8
Revises: 
Create Date: 2026-07-31 08:52:51.326324
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ddf7460703a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('resource', sa.String(length=240), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_admin_sessions_user_id'), 'admin_sessions', ['user_id'], unique=False)
    op.create_table('policy_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'revision')
    )
    op.create_index(op.f('ix_policy_revisions_organization_id'), 'policy_revisions', ['organization_id'], unique=False)
    op.create_table('schedule_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'revision')
    )
    op.create_index(op.f('ix_schedule_revisions_organization_id'), 'schedule_revisions', ['organization_id'], unique=False)
    op.create_table('device_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('schedule_revision_id', sa.String(length=36), nullable=True),
    sa.Column('policy_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['policy_revision_id'], ['policy_revisions.id'], ),
    sa.ForeignKeyConstraint(['schedule_revision_id'], ['schedule_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_index(op.f('ix_device_groups_organization_id'), 'device_groups', ['organization_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('installation_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('app_version', sa.String(length=40), nullable=False),
    sa.Column('plugin_version', sa.String(length=40), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('current_status', sa.String(length=40), nullable=False),
    sa.Column('current_title', sa.String(length=200), nullable=False),
    sa.Column('schedule_revision', sa.Integer(), nullable=False),
    sa.Column('policy_revision', sa.Integer(), nullable=False),
    sa.Column('last_cursor', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_group_id'), 'devices', ['group_id'], unique=False)
    op.create_index(op.f('ix_devices_installation_id'), 'devices', ['installation_id'], unique=True)
    op.create_index(op.f('ix_devices_token_hash'), 'devices', ['token_hash'], unique=True)
    op.create_table('pairing_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_codes_code_hash'), 'pairing_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_pairing_codes_group_id'), 'pairing_codes', ['group_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cursor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_cursor'), 'commands', ['cursor'], unique=True)
    op.create_table('diagnostic_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('app_version', sa.String(length=40), nullable=False),
    sa.Column('plugin_version', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_reports_device_id'), 'diagnostic_reports', ['device_id'], unique=False)
    op.create_table('command_acknowledgements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', 'device_id')
    )
    op.create_index(op.f('ix_command_acknowledgements_command_id'), 'command_acknowledgements', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_acknowledgements_device_id'), 'command_acknowledgements', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_acknowledgements_device_id'), table_name='command_acknowledgements')
    op.drop_index(op.f('ix_command_acknowledgements_command_id'), table_name='command_acknowledgements')
    op.drop_table('command_acknowledgements')
    op.drop_index(op.f('ix_diagnostic_reports_device_id'), table_name='diagnostic_reports')
    op.drop_table('diagnostic_reports')
    op.drop_index(op.f('ix_commands_cursor'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_pairing_codes_group_id'), table_name='pairing_codes')
    op.drop_index(op.f('ix_pairing_codes_code_hash'), table_name='pairing_codes')
    op.drop_table('pairing_codes')
    op.drop_index(op.f('ix_devices_token_hash'), table_name='devices')
    op.drop_index(op.f('ix_devices_installation_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_group_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_groups_organization_id'), table_name='device_groups')
    op.drop_table('device_groups')
    op.drop_index(op.f('ix_schedule_revisions_organization_id'), table_name='schedule_revisions')
    op.drop_table('schedule_revisions')
    op.drop_index(op.f('ix_policy_revisions_organization_id'), table_name='policy_revisions')
    op.drop_table('policy_revisions')
    op.drop_index(op.f('ix_admin_sessions_user_id'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_token_hash'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###